### ISSUE TITLE
random player vanish when not supporsed

### ISSUE THREAD

**Issue by Thunder33345** [iksaku/VanishNoPacket#1]
some other player get invisible even they cant access the cmd
i will have to vanish him then unvanish to solve it
2 some of my usr say everyone is vanish to them(cant confirm since that is not seen by me)
sorry i dont really know how to reproduce this

**Comment by iksaku** [comment]
I can't reproduce this error, do you remember that PocketMine-MP had a glitch about invisible players before this Plugin was created?

**Comment by Thunder33345** [comment]
yes @iksaku ither myself cant confirm
but most of my client says there invisible player
maybe lets wait other to confirm
i cant sure if /reload
bugs out with the plugin
